export const difficulties = [
  {
    name: '伞剑的守护',
    beginnerLevel: 3,
    intermediateLevel: 6,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '道成夙怨',
    beginnerLevel: 3,
    intermediateLevel: 6,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '荒川之怒',
    beginnerLevel: 3,
    intermediateLevel: 6,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '暴风之巅',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '海怪的温柔',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '狐生百魅',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '雨女的等候',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 6,
    masterLevel: 10,
    specials: {
      7: '4兔子加季',
    },
  },
  {
    name: '红叶的羁绊',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '青灯百物语',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '鲜血之月',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '意志的觉醒',
    beginnerLevel: 3,
    intermediateLevel: 4,
    expertLevel: 6,
    masterLevel: 10,
  },
  {
    name: '黄泉彼岸',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 6,
    masterLevel: 10,
  },
  {
    name: '河畔童谣',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 10,
    masterLevel: 0,
  },
  {
    name: '妖刀之秘籍',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 10,
    masterLevel: 0,
  },
  {
    name: '雪之回忆',
    beginnerLevel: 2,
    intermediateLevel: 5,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '夏之风物诗',
    beginnerLevel: 1,
    intermediateLevel: 3,
    expertLevel: 7,
    masterLevel: 0,
  },
  {
    name: '拾花旧忆',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '盛宴终刻',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '逐路之争',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 0,
    masterLevel: 0,
    specials: {
      5: '四兔子+季',
      6: '四兔子+季',
    },
  },
  {
    name: '烽火寄情',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '夜雪无声',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 5,
    masterLevel: 0,
  },
  {
    name: '浪客远道',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '瓜士无双',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '征服世界',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 6,
    masterLevel: 0,
  },
];

export const RewardType = {
  gold: '金币',
  jades: '勾玉',
  ticket: '神秘的符咒',
  avatarFrame: '头像框',
  costume: '皮肤',
  blackDharma: '御行达摩',
  blueDharma: '大吉达摩',
  redDharma: '招福达摩',
  twoStarWhiteDharma: '两星奉为达摩',
  fourStarWhiteDharma: '四星奉为达摩',
  sixStarSoul: '六星随机御魂',
  shards: '式神碎片',
  goldenSkins: '金蛇皮',
};

export const information = [
  {
    name: '山兔大暴走',
    imageAlt: '山兔',
    instances: [
      {
        level: 1,
        name: '开心的山兔',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '安静的山兔',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '严肃的山兔',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '认真的山兔',
        rewardType: RewardType.jades,
        rewardAmount: 75,
      },
      {
        level: 5,
        name: '嘟嘴的山兔',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '不开心的山兔',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 7,
        name: '闹脾气的山兔',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '生气的山兔',
        rewardType: RewardType.ticket,
        rewardAmount: 2,
      },
      {
        level: 9,
        name: '愤怒的山兔',
        rewardType: RewardType.avatarFrame,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '暴走的山兔',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '红叶的羁绊',
    imageName: 'guinvhongye.png',
    imageAlt: '红叶',
    instances: [
      {
        level: 1,
        name: '壹·邂逅',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·别离',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·暮想',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·唆摆',
        rewardType: RewardType.redDharma,
        rewardAmount: 3,
      },
      {
        level: 5,
        name: '伍·意乱',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·妖变',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·堕落',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·痴迷',
        rewardType: RewardType.avatarFrame,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·苦恋',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·羁绊',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '妖刀之秘籍',
    imageAlt: '妖刀',
    instances: [
      {
        level: 1,
        name: '妖刀·壹式',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        description: '同行式神待霄姑获鸟随便打',
      },
      {
        level: 2,
        name: '妖刀·贰式',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '妖刀·叁式',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '妖刀·肆式',
        rewardType: RewardType.redDharma,
        rewardAmount: 3,
      },
      {
        level: 5,
        name: '妖刀·伍式',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '妖刀·陆式',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '妖刀·柒式',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
      },
      {
        level: 8,
        name: '妖刀·捌式',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '妖刀·玖式',
        rewardType: RewardType.avatarFrame,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '妖刀·拾式',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '河畔童谣',
    imageAlt: '河童',
    instances: [
      {
        level: 1,
        name: '壹·稚气',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·童真',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·眺望',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·跋涉',
        rewardType: RewardType.redDharma,
        rewardAmount: 3,
      },
      {
        level: 5,
        name: '伍·舞蹈',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·无间',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·孤傲',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
      },
      {
        level: 8,
        name: '捌·浩瀚',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·泡沫',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·离歌',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '雨女的等候',
    imageAlt: '雨女',
    instances: [
      {
        level: 1,
        name: '壹·月明',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
      },
      {
        level: 2,
        name: '贰·对饮',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
      },
      {
        level: 3,
        name: '叁·惮寒',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 4,
        name: '肆·无怨',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 5,
        name: '伍·悲喜',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·聚散',
        rewardType: RewardType.jades,
        rewardAmount: 200,
      },
      {
        level: 7,
        name: '柒·阴阳',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·盈亏',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·恒远',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·婵娟',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '荒川之怒',
    imageAlt: '荒川',
    instances: [
      {
        level: 1,
        name: '壹·涟漪',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·帆影',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·暗流',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·汨汨',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·澎湃',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 6,
        name: '陆·汹涌',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
      },
      {
        level: 7,
        name: '柒·鲸波',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·狂澜',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·浩瀚',
        rewardType: RewardType.sixStarSoul,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·暴怒',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '暴风之巅',
    imageAlt: '大天狗',
    instances: [
      {
        level: 1,
        name: '壹·初拂',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·轻扬',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·萧瑟',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·扶摇',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·升腾',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 6,
        name: '陆·呼啸',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
      },
      {
        level: 7,
        name: '柒·狂袭',
        rewardType: RewardType.ticket,
        rewardAmount: 2,
      },
      {
        level: 8,
        name: '捌·怒号',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·暗涌',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·冲巅',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '夏之风物诗',
    imageAlt: '镰鼬',
    instances: [
      {
        level: 1,
        name: '壹·夕立',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·风铃',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·蝉鸣',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·凉扇',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·萤笼',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·西瓜',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·刨冰',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·花火',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·海',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·夏祭',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '意志的觉醒',
    imageAlt: '小鹿男',
    instances: [
      {
        level: 1,
        name: '壹·孑然',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
      },
      {
        level: 2,
        name: '贰·伎薄',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
      },
      {
        level: 3,
        name: '叁·初遇',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 4,
        name: '肆·伙伴',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 5,
        name: '伍·守望',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 6,
        name: '陆·肝胆',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 7,
        name: '柒·恩义',
        rewardType: RewardType.jades,
        rewardAmount: 200,
      },
      {
        level: 8,
        name: '捌·报答',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·坚持',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·觉醒',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '海怪的温柔',
    imageAlt: '海坊主',
    instances: [
      {
        level: 1,
        name: '壹·平静',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
      },
      {
        level: 2,
        name: '贰·暴雨',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
      },
      {
        level: 3,
        name: '叁·规劝',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 4,
        name: '肆·惶恐',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 5,
        name: '伍·隐忍',
        rewardType: RewardType.shards,
        rewardAmount: 35,
      },
      {
        level: 6,
        name: '陆·生畏',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 7,
        name: '柒·狂躁',
        rewardType: RewardType.jades,
        rewardAmount: 200,
      },
      {
        level: 8,
        name: '捌·惴惴',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·黯然',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·轮回',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '青灯百物语',
    imageAlt: '青行灯',
    instances: [
      {
        level: 1,
        name: '壹·夜临',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
      },
      {
        level: 2,
        name: '贰·青灯',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
      },
      {
        level: 3,
        name: '叁·潜伏',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 4,
        name: '肆·怪谈',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 5,
        name: '伍·搜集',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 6,
        name: '陆·细述',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 7,
        name: '柒·百物语',
        rewardType: RewardType.jades,
        rewardAmount: 200,
      },
      {
        level: 8,
        name: '捌·烛灭',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·游荡',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·永夜',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '鲜血之月',
    imageAlt: '吸血姬',
    instances: [
      {
        level: 1,
        name: '壹·暗夜',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
      },
      {
        level: 2,
        name: '贰·失控',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
      },
      {
        level: 3,
        name: '叁·扑灭',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 4,
        name: '肆·撕咬',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 5,
        name: '伍·突变',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 6,
        name: '陆·荤腥',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 7,
        name: '柒·渐现',
        rewardType: RewardType.goldenSkins,
        rewardAmount: 50,
      },
      {
        level: 8,
        name: '捌·嗜血',
        rewardType: RewardType.ticket,
        rewardAmount: 3,
      },
      {
        level: 9,
        name: '玖·昼伏',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·血月',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '狐生百魅',
    imageAlt: '妖狐',
    instances: [
      {
        level: 1,
        name: '壹·面具',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·折扇',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·小生',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·找寻',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·风雅',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·爱意',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·呢喃',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·轻语',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·命运之人',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·爱的深渊',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '黄泉彼岸',
    imageAlt: '彼岸花',
    instances: [
      {
        level: 1,
        name: '壹·誓诺',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·脆弱',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·恐惧',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·鲜红',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·花海',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·汲取',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·养分',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·能量',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·彼岸',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·黄泉',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·激战！',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '道成夙怨',
    imageAlt: '清姬',
    instances: [
      {
        level: 1,
        name: '壹·相遇',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·倾心',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·许诺',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·等待',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·失言',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·追寻',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·苦求',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·爱憎',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·焚烧',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·灰灭',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·激战！',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '雪之回忆',
    imageAlt: '雪童子',
    instances: [
      {
        level: 1,
        name: '壹·风雪',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·寂寞',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·雪偶',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·造访',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·惊喜',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·陪伴',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·笑容',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·惆怅',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·悄离',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·回忆',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·激战！',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
];
