import { presets } from '../../data/presets';

export const difficulties = [
  {
    name: '伞剑的守护',
    beginnerLevel: 3,
    intermediateLevel: 6,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '道成夙怨',
    beginnerLevel: 3,
    intermediateLevel: 6,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '荒川之怒',
    beginnerLevel: 3,
    intermediateLevel: 6,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '暴风之巅',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '海怪的温柔',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '狐生百魅',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '雨女的等候',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 6,
    masterLevel: 10,
    specials: {
      7: '4兔子加季',
    },
  },
  {
    name: '红叶的羁绊',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '青灯百物语',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 7,
    masterLevel: 10,
  },
  {
    name: '鲜血之月',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 8,
    masterLevel: 10,
  },
  {
    name: '意志的觉醒',
    beginnerLevel: 3,
    intermediateLevel: 4,
    expertLevel: 6,
    masterLevel: 10,
  },
  {
    name: '黄泉彼岸',
    beginnerLevel: 3,
    intermediateLevel: 5,
    expertLevel: 6,
    masterLevel: 10,
  },
  {
    name: '河畔童谣',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 10,
    masterLevel: 0,
  },
  {
    name: '妖刀之秘籍',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 10,
    masterLevel: 0,
  },
  {
    name: '雪之回忆',
    beginnerLevel: 2,
    intermediateLevel: 5,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '夏之风物诗',
    beginnerLevel: 1,
    intermediateLevel: 3,
    expertLevel: 7,
    masterLevel: 0,
  },
  {
    name: '拾花旧忆',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '盛宴终刻',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '逐路之争',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 0,
    masterLevel: 0,
    specials: {
      5: '四兔子+季',
      6: '四兔子+季',
    },
  },
  {
    name: '烽火寄情',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '夜雪无声',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 5,
    masterLevel: 0,
  },
  {
    name: '浪客远道',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '瓜士无双',
    beginnerLevel: 2,
    intermediateLevel: 3,
    expertLevel: 6,
    masterLevel: 0,
  },
  {
    name: '征服世界',
    beginnerLevel: 2,
    intermediateLevel: 4,
    expertLevel: 6,
    masterLevel: 0,
  },
];

export const RewardType = {
  gold: '金币',
  jades: '勾玉',
  ticket: '神秘的符咒',
  avatarFrame: '头像框',
  costume: '皮肤',
  blackDharma: '御行达摩',
  blueDharma: '大吉达摩',
  redDharma: '招福达摩',
  twoStarWhiteDharma: '两星奉为达摩',
  fourStarWhiteDharma: '四星奉为达摩',
  sixStarSoul: '六星随机御魂',
  shards: '式神碎片',
  goldenSkins: '金蛇皮',
};

export const information = [
  {
    name: '山兔大暴走',
    imageAlt: '山兔',
    imageName: 'yamausagi.png',
    instances: [
      {
        level: 1,
        name: '开心的山兔',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        requirements: [['同行待霄姑获鸟']],
      },
      {
        level: 2,
        name: '安静的山兔',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '严肃的山兔',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '认真的山兔',
        rewardType: RewardType.jades,
        rewardAmount: 75,
      },
      {
        level: 5,
        name: '嘟嘴的山兔',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '不开心的山兔',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 7,
        name: '闹脾气的山兔',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '生气的山兔',
        rewardType: RewardType.ticket,
        rewardAmount: 2,
      },
      {
        level: 9,
        name: '愤怒的山兔',
        rewardType: RewardType.avatarFrame,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '暴走的山兔',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '红叶的羁绊',
    imageName: 'momiji.png',
    imageAlt: '红叶',
    instances: [
      {
        level: 1,
        name: '壹·邂逅',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·别离',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·暮想',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·唆摆',
        rewardType: RewardType.redDharma,
        rewardAmount: 3,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·意乱',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·妖变',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·堕落',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·痴迷',
        rewardType: RewardType.avatarFrame,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·苦恋',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 10,
        name: '拾·羁绊',
        rewardType: RewardType.costume,
        rewardAmount: 1,
        ...presets[3],
      },
    ],
  },
  {
    name: '妖刀之秘籍',
    imageAlt: '妖刀',
    imageName: 'yoto-hime.png',
    instances: [
      {
        level: 1,
        name: '妖刀·壹式',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '妖刀·贰式',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '妖刀·叁式',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '妖刀·肆式',
        rewardType: RewardType.redDharma,
        rewardAmount: 3,
        ...presets[1],
      },
      {
        level: 5,
        name: '妖刀·伍式',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[2],
      },
      {
        level: 6,
        name: '妖刀·陆式',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 7,
        name: '妖刀·柒式',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
        ...presets[3],
      },
      {
        level: 8,
        name: '妖刀·捌式',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '妖刀·玖式',
        rewardType: RewardType.avatarFrame,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 10,
        name: '妖刀·拾式',
        rewardType: RewardType.costume,
        rewardAmount: 1,
        ...presets[3],
      },
    ],
  },
  {
    name: '河畔童谣',
    imageAlt: '河童',
    imageName: 'kappa.png',
    instances: [
      {
        level: 1,
        name: '壹·稚气',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·童真',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·眺望',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·跋涉',
        rewardType: RewardType.redDharma,
        rewardAmount: 3,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·舞蹈',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·无间',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·孤傲',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·浩瀚',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·泡沫',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 10,
        name: '拾·离歌',
        rewardType: RewardType.costume,
        rewardAmount: 1,
        ...presets[3],
      },
    ],
  },
  {
    name: '雨女的等候',
    imageAlt: '雨女',
    imageName: 'ame-onna.png',
    instances: [
      {
        level: 1,
        name: '壹·月明',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·对饮',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·惮寒',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·无怨',
        rewardType: RewardType.twoStarWhiteDharma,
        rewardAmount: 1,
        ...presets[1],
      },
      {
        level: 5,
        name: '伍·悲喜',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·聚散',
        rewardType: RewardType.jades,
        rewardAmount: 200,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·阴阳',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 8,
        name: '捌·盈亏',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·恒远',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[3],
        description:
          '真旅居系统麓铭大岳丸单刷,非常不稳定,主要是三回目管狐的伤害很高,大岳丸可能会在怪一轮攻击后被直接击杀,只要能在死之前杀一只管狐就稳过了.',
      },
      {
        level: 10,
        name: '拾·婵娟',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '荒川之怒',
    imageAlt: '荒川',
    imageName: 'lord-arakawa.png',
    instances: [
      {
        level: 1,
        name: '壹·涟漪',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·帆影',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·暗流',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·汨汨',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[1],
      },
      {
        level: 5,
        name: '伍·澎湃',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 6,
        name: '陆·汹涌',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·鲸波',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·狂澜',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 9,
        name: '玖·浩瀚',
        rewardType: RewardType.sixStarSoul,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 10,
        name: '拾·暴怒',
        rewardType: RewardType.costume,
        rewardAmount: 1,
        ...presets[4],
      },
    ],
  },
  {
    name: '暴风之巅',
    imageAlt: '大天狗',
    imageName: 'ootengu.png',
    instances: [
      {
        level: 1,
        name: '壹·初拂',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·轻扬',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·萧瑟',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·扶摇',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[2],
        description: `${presets[2]}.三回目小僧,单输出的话会被反弹死,需要多一个输出.`,
      },
      {
        level: 5,
        name: '伍·升腾',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 6,
        name: '陆·呼啸',
        rewardType: RewardType.gold,
        rewardAmount: 200000,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·狂袭',
        rewardType: RewardType.ticket,
        rewardAmount: 2,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·怒号',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 9,
        name: '玖·暗涌',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 10,
        name: '拾·冲巅',
        rewardType: RewardType.costume,
        rewardAmount: 1,
        ...presets[4],
      },
    ],
  },
  {
    name: '伞剑的守护',
    imageAlt: '姑获鸟',
    imageName: 'ubume.png',
    instances: [
      {
        level: 1,
        name: '壹·鹤笠',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·伞护',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·执剑',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·怜子',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·养育',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·陪伴',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·远行',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·牵挂',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·怀情',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 10,
        name: '拾·慈心',
        rewardType: RewardType.costume,
        rewardAmount: 1,
        ...presets[4],
      },
    ],
  },
  {
    name: '夏之风物诗',
    imageAlt: '镰鼬',
    imageName: 'kamaitachi.png',
    instances: [
      {
        level: 1,
        name: '壹·夕立',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·风铃',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[2],
      },
      {
        level: 3,
        name: '叁·蝉鸣',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[3],
      },
      {
        level: 4,
        name: '肆·凉扇',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[3],
      },
      {
        level: 5,
        name: '伍·萤笼',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[3],
      },
      {
        level: 6,
        name: '陆·西瓜',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·刨冰',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·花火',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·海',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·夏祭',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '意志的觉醒',
    imageAlt: '小鹿男',
    imageName: 'shishio.png',
    instances: [
      {
        level: 1,
        name: '壹·孑然',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·伎薄',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·初遇',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·伙伴',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·守望',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[3],
        description:
          '真旅居系统麓铭大岳丸单刷,三回目小僧还是挺危险的，可以考虑先单点了，再开技能',
      },
      {
        level: 6,
        name: '陆·肝胆',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·恩义',
        rewardType: RewardType.jades,
        rewardAmount: 200,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·报答',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 9,
        name: '玖·坚持',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 10,
        name: '拾·觉醒',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '海怪的温柔',
    imageAlt: '海坊主',
    imageName: 'umibozu.png',
    instances: [
      {
        level: 1,
        name: '壹·平静',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·暴雨',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·规劝',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·惶恐',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·隐忍',
        rewardType: RewardType.shards,
        rewardAmount: 35,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·生畏',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·狂躁',
        rewardType: RewardType.jades,
        rewardAmount: 200,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·惴惴',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·黯然',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[3],
        description:
          '真旅居系统麓铭大岳丸可以单刷，不过太肉了，三分半才能打完，可能用完成的阵容打更好',
      },
      {
        level: 10,
        name: '拾·轮回',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '青灯百物语',
    imageAlt: '青行灯',
    imageName: 'aoadon.png',
    instances: [
      {
        level: 1,
        name: '壹·夜临',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·青灯',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·潜伏',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·怪谈',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·搜集',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·细述',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·百物语',
        rewardType: RewardType.jades,
        rewardAmount: 200,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·烛灭',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 9,
        name: '玖·游荡',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·永夜',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '鲜血之月',
    imageAlt: '吸血姬',
    imageName: 'vampira.png',
    instances: [
      {
        level: 1,
        name: '壹·暗夜',
        rewardType: RewardType.redDharma,
        rewardAmount: 1,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·失控',
        rewardType: RewardType.gold,
        rewardAmount: 20000,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·扑灭',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·撕咬',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·突变',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·荤腥',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[4],
      },
      {
        level: 7,
        name: '柒·渐现',
        rewardType: RewardType.goldenSkins,
        rewardAmount: 50,
        ...presets[4],
      },
      {
        level: 8,
        name: '捌·嗜血',
        rewardType: RewardType.ticket,
        rewardAmount: 3,
        ...presets[4],
      },
      {
        level: 9,
        name: '玖·昼伏',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·血月',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '狐生百魅',
    imageAlt: '妖狐',
    imageName: 'youko.png',
    instances: [
      {
        level: 1,
        name: '壹·面具',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·折扇',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·小生',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·找寻',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·风雅',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·爱意',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 7,
        name: '柒·呢喃',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 8,
        name: '捌·轻语',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·命运之人',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 10,
        name: '拾·爱的深渊',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '黄泉彼岸',
    imageAlt: '彼岸花',
    imageName: 'higanbana.png',
    instances: [
      {
        level: 1,
        name: '壹·誓诺',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·脆弱',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·恐惧',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·鲜红',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·花海',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[3],
      },
      {
        level: 6,
        name: '陆·汲取',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·养分',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·能量',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·彼岸',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[3],
        description: '麓铭大岳丸单挂,要打5分钟,考虑不急着刷',
      },
      {
        level: 10,
        name: '拾·黄泉',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·激战！',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '道成夙怨',
    imageAlt: '清姬',
    imageName: 'kiyohime.png',
    instances: [
      {
        level: 1,
        name: '壹·相遇',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·倾心',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·许诺',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·等待',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·失言',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[2],
      },
      {
        level: 6,
        name: '陆·追寻',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 7,
        name: '柒·苦求',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 8,
        name: '捌·爱憎',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 9,
        name: '玖·焚烧',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 10,
        name: '拾·灰灭',
        rewardType: RewardType.costume,
        rewardAmount: 1,
        ...presets[3],
      },
      {
        level: 11,
        name: '番外·激战！',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[3],
      },
    ],
  },
  {
    name: '雪之回忆',
    imageAlt: '雪童子',
    imageName: 'yuki.png',
    instances: [
      {
        level: 1,
        name: '壹·风雪',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
        ...presets[1],
      },
      {
        level: 2,
        name: '贰·寂寞',
        rewardType: RewardType.jades,
        rewardAmount: 50,
        ...presets[1],
      },
      {
        level: 3,
        name: '叁·雪偶',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
        ...presets[1],
      },
      {
        level: 4,
        name: '肆·造访',
        rewardType: RewardType.jades,
        rewardAmount: 100,
        ...presets[2],
      },
      {
        level: 5,
        name: '伍·惊喜',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
        ...presets[4],
      },
      {
        level: 6,
        name: '陆·陪伴',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 7,
        name: '柒·笑容',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
        ...presets[4],
      },
      {
        level: 8,
        name: '捌·惆怅',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·悄离',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·回忆',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·激战！',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '征服世界',
    imageAlt: '金鱼姬',
    imageName: 'kingyo.png',
    instances: [
      {
        level: 1,
        name: '壹·温柔',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·玩耍',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·切磋',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·保佑',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·花',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·背负',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·追求',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·酒',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·趣味',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·归家',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·可爱！',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '呱士无双',
    imageAlt: '青蛙瓷器',
    imageName: 'jikikaeru.png',
    instances: [
      {
        level: 1,
        name: '壹·直立',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·断幺九',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·两立直',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·三杠子',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·三暗刻',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·小三元',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·混一色',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·清一色',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·大三元',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·大四喜',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·流局',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '安梦奇缘',
    imageAlt: '食梦貘',
    imageName: 'yumikui.png',
    instances: [
      {
        level: 1,
        name: '壹·如梦',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·记忆',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·庙宇',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·奔跑',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·神佑',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·守护',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·独立',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·相拥',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·前尘',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·终曲',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·梦醒',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '浪客远道',
    imageAlt: '犬神',
    imageName: 'inugami.png',
    instances: [
      {
        level: 1,
        name: '壹·奔走',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·斩恶',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·血泊',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·安眠',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·重生',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·挥刃',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·信使',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·复仇',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·怒火',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·愧疚',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·相友',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '山巅之禁',
    imageAlt: '一目连',
    imageName: 'ichimokuren.png',
    instances: [
      {
        level: 1,
        name: '壹·探究',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·纵然',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·拆招',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·心愿',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·苏醒',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·弑恶',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·困兽',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·恶斗',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·无边',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·拯救',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·信任',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '夜雪无声',
    imageAlt: '雪女',
    imageName: 'yuki-onna.png',
    instances: [
      {
        level: 1,
        name: '壹·初雪',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·无瑕',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·霜衣',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·白鹤',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·飞花',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·枕梦',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·粉黛',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·戏说',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·欢声',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·落幕',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·快雪时晴',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '骁武浪升',
    imageAlt: '骁浪荒川',
    imageName: 'sp-arakawa.png',
    instances: [
      {
        level: 1,
        name: '壹·入海',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·崇云',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·远野',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·峻山',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·冥岸',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·高天',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·蔚海',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·逐浪',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·孤屿',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·止境',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·归帆',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '烽火寄请',
    imageAlt: '小袖之手',
    imageName: 'kosodenote.png',
    instances: [
      {
        level: 1,
        name: '壹·家书',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·金戈',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·久别',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·烽火',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·山重',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·旧梦',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·守候',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·期盼',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·清平',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·寄情',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·牵思',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '逐路之争',
    imageAlt: '孟婆',
    imageName: 'mouba.png',
    instances: [
      {
        level: 1,
        name: '壹·庆典',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·朋友',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·试胆',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·鬼使',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·冥府',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·出发',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·意外',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·谜团',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·危机',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·真相',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·尾声',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '盛宴终刻',
    imageAlt: '海忍',
    imageName: 'kaininn.png',
    instances: [
      {
        level: 1,
        name: '壹·宴启',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·筳酒',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·珍馐',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·旧辞',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·黯焰',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·忍歌',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·残影',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·虚宴',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·终舞',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·宴尽',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·孤伶',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '拾花旧忆',
    imageAlt: '傀儡师',
    imageName: 'puppeteer.png',
    instances: [
      {
        level: 1,
        name: '壹·尘影',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·葬歌',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·初遇',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·镌琢',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·心脏',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·牵丝',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·丁香',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·逃离',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·寻觅',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·两隔',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·偶遇',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
  {
    name: '流萤之夏',
    imageAlt: '虫师',
    imageName: 'mushishi.png',
    instances: [
      {
        level: 1,
        name: '壹·夏影',
        rewardType: RewardType.gold,
        rewardAmount: 10000,
      },
      {
        level: 2,
        name: '贰·问夏',
        rewardType: RewardType.jades,
        rewardAmount: 50,
      },
      {
        level: 3,
        name: '叁·藏茧',
        rewardType: RewardType.gold,
        rewardAmount: 50000,
      },
      {
        level: 4,
        name: '肆·缚心',
        rewardType: RewardType.jades,
        rewardAmount: 100,
      },
      {
        level: 5,
        name: '伍·长伴',
        rewardType: RewardType.gold,
        rewardAmount: 100000,
      },
      {
        level: 6,
        name: '陆·唤心',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
      {
        level: 7,
        name: '柒·流萤',
        rewardType: RewardType.blueDharma,
        rewardAmount: 1,
      },
      {
        level: 8,
        name: '捌·牵思',
        rewardType: RewardType.fourStarWhiteDharma,
        rewardAmount: 1,
      },
      {
        level: 9,
        name: '玖·等待',
        rewardType: RewardType.blackDharma,
        rewardAmount: 1,
      },
      {
        level: 10,
        name: '拾·归处',
        rewardType: RewardType.costume,
        rewardAmount: 1,
      },
      {
        level: 11,
        name: '番外·梦醒',
        rewardType: RewardType.ticket,
        rewardAmount: 1,
      },
    ],
  },
];
